# Autogenerated wrapper script for hiredis_jll for i686-linux-musl
export libhiredis, libhiredis_ssl

using OpenSSL_jll
JLLWrappers.@generate_wrapper_header("hiredis")
JLLWrappers.@declare_library_product(libhiredis, "libhiredis.so.1.1.0")
JLLWrappers.@declare_library_product(libhiredis_ssl, "libhiredis_ssl.so.1.1.0")
function __init__()
    JLLWrappers.@generate_init_header(OpenSSL_jll)
    JLLWrappers.@init_library_product(
        libhiredis,
        "lib/libhiredis.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libhiredis_ssl,
        "lib/libhiredis_ssl.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
